apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: openshift-ansible-istio-installer-job
  name: openshift-ansible-istio-installer-job
  namespace: istio-system
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: openshift-ansible-istio-installer-job
    spec:
      containers:
      - env:
        - name: INVENTORY_FILE
          value: /tmp/inventory/istio.inventory
        - name: PLAYBOOK_FILE
          value: playbooks/openshift-istio/config.yml
        - name: OPTS
          value: -vvv
        - name: ANSIBLE_GATHER_TIMEOUT
          value: "30"
        image: docker.io/maistra/origin-ansible:0.2.0
        imagePullPolicy: IfNotPresent
        name: openshift-ansible-istio-installer-job
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/origin/master
          name: configdir
        - mountPath: /tmp/inventory/
          name: configmap
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: openshift-ansible
      serviceAccountName: openshift-ansible
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/origin/master
          type: ""
        name: configdir
      - configMap:
          defaultMode: 420
          name: install.istio.inventory
        name: configmap

